apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: healthchecks.example.com
  namespace: default
spec:
  scope: Namespaced 
  group: example.com
  names:
    kind: HealthCheck 
    plural: healthchecks
    singular: healthcheck 
    shortNames:
      - hc 
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                port:
                  type: integer
                  format: int32
                timeout:
                  type: integer
                  format: int32
                serv_namespace:
                  type: string 
              required: ["serv_namespace", "port", "timeout"]
      additionalPrinterColumns:
        - name: Service_Namespace
          type: string
          jsonPath: .spec.serv_namespace
        - name: Port 
          type: integer
          jsonPath: .spec.port
        - name:  Timeout 
          type: integer 
          jsonPath: .spec.timeout
