apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
  name: node-health-check-operator-rs-role
rules:
- apiGroups:
  - ""
  - healthchecks.example.com
  - example.com
  - test.com
  - node.k8s.linode.com
  resources:
  - nodes
  - pods 
  - healthchecks
  - hc
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods 
  verbs:
  - get
  - watch
  - list
